import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import MeuPrimeiroComponente from '@/components/MeuPrimeiroComponente';
import ConteudoComponente from '@/components/ConteudoComponent';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image src="/img/logo2.jpg" alt="Logo" width={100} height={200} />

        <ConteudoComponente titulo="Links">
          <MeuPrimeiroComponente
            titulo="Curriculo"
            subtitulo="Clique neste componente para ver o curriculo"
            link="./img/curriculum.jpg"
          />

          <MeuPrimeiroComponente
            titulo="GitHub"
            subtitulo="Clique neste componente para ver o meu github"
            link="#"
          />
        </ConteudoComponente>
        <ConteudoComponente titulo="Formações">
          <h2>Graduação</h2>
          <p>Lorem ipsum</p>
          <br />
          <h2>Graduação</h2>
          <p>Lorem ipsum</p>
        </ConteudoComponente>
      </main>
    </>
  );
}
